(function(){
  'use strict';
  const $=s=>document.querySelector(s);
  const esc2=s=>typeof esc==='function'?esc(s):String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const tr=s=>window.trV24?window.trV24(s):s;
  function ytId(url){const m=String(url||'').match(/(?:youtube\.com\/(?:watch\?v=|shorts\/|embed\/)|youtu\.be\/)([A-Za-z0-9_-]{6,})/i);return m?m[1]:''}
  async function me(){try{const r=await fetch('/api/account/me',{cache:'no-store'});return await r.json()}catch{return {loggedIn:false}}}
  let otpChallenge='';
  async function accountAuthV26(ev,mode){ev.preventDefault();const f=new FormData(ev.currentTarget),email=String(f.get('email')||'').trim(),password=String(f.get('password')||'');const submit=ev.currentTarget.querySelector('button[type=submit]');if(submit){submit.disabled=true;submit.textContent='BITTE WARTEN…'}try{const r=await fetch('/api/auth/'+mode,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const d=await r.json();toast(d.message||'');if(d.requires2fa){otpChallenge=d.challenge||'';const box=$('#otpBox');if(box)box.innerHTML=`<div class="otp-panel"><div class="otp-icon">✉</div><h2>E-Mail bestätigen</h2><p>Wir haben einen 6-stelligen Bestätigungscode an <b>${esc2(email)}</b> gesendet.</p><form onsubmit="verifyOtpV26(event)"><input id="otpCode" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" autocomplete="one-time-code" required placeholder="000000"><button class="btn primary login-submit">CODE BESTÄTIGEN</button></form><button class="resend" type="button" onclick="resendOtpV26('${mode}')">CODE ERNEUT SENDEN</button><small>Ohne gültigen Code wird kein Login erstellt.</small></div>`;$('#otpCode')?.focus()}else if(d.success)location.reload()}finally{if(submit){submit.disabled=false;submit.textContent=mode==='login'?'ANMELDEN':'KONTO ERSTELLEN'}}}
  window.accountAuth=accountAuthV26;
  window.verifyOtpV26=async function(ev){ev.preventDefault();const code=String($('#otpCode')?.value||'').trim();const r=await fetch('/api/auth/verify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({challenge:otpChallenge,code})});const d=await r.json();toast(d.message||'');if(d.success)location.reload()};
  window.resendOtpV26=async function(mode){const form=document.querySelector(mode==='login'?'#loginForm':'#registerForm');if(form)await accountAuthV26({preventDefault:()=>{},currentTarget:form},mode)};
  
  async function renderVideos(){
    let d={trailer:null,creators:[]};try{const r=await fetch('/api/videos?_='+Date.now(),{cache:'no-store'});if(r.ok)d=await r.json()}catch{}
    const trailer=d.trailer&&ytId(d.trailer.url)?d.trailer:null;
    const creators=(d.creators||[]).filter(v=>ytId(v.url));
    const card=v=>{const id=ytId(v.url),title=esc2(v.title||'Pet Horizon Video'),creator=esc2(v.creator||'Content Creator');return `<article class="creator-video-card"><div class="creator-video-thumb"><img src="https://i.ytimg.com/vi/${id}/hqdefault.jpg" alt="${title}" loading="lazy"><button class="video-play" onclick="openVideoV24('${id}','${title.replace(/'/g,"\\'")}','${creator.replace(/'/g,"\\'")}')">▶</button></div><div class="creator-video-info"><small>${creator}</small><h3>${title}</h3><button class="btn" onclick="openVideoV24('${id}','${title.replace(/'/g,"\\'")}','${creator.replace(/'/g,"\\'")}')">${tr('ÖFFNEN')}</button></div></article>`};
    const trailerHtml=trailer?`<div class="trailer-player"><iframe src="https://www.youtube.com/embed/${ytId(trailer.url)}?rel=0" title="${esc2(trailer.title||'Pet Horizon Trailer')}" allow="autoplay; encrypted-media; picture-in-picture" allowfullscreen></iframe></div><div class="video-meta"><small>GAME TRAILER</small><h2>${esc2(trailer.title)}</h2><p>${esc2(trailer.description||'Nur von JaniboyGames freigegebene Videos werden öffentlich angezeigt.')}</p></div>`:`<div class="video-empty"><div class="video-empty-icon">▶</div><b>NOCH NICHT VERFÜGBAR</b><span>Noch kein freigegebener Trailer vorhanden.</span></div>`;
    $('#app').innerHTML=`<main class="page videos-page"><div class="page-head"><small>CONTENT CREATOR</small><h1>VIDEOS</h1><p>Nur von JaniboyGames freigegebene Videos werden hier öffentlich angezeigt.</p></div><section class="trailer-section"><div class="section-title"><div><small>TRAILER</small><h2>GAME TRAILER</h2></div></div><div class="trailer-card">${trailerHtml}</div></section><section class="creator-section"><div class="section-title"><div><small>CONTENT CREATOR</small><h2>CREATOR VIDEOS</h2></div><span class="section-note">FREIGEGEBEN</span></div><div class="creator-video-grid">${creators.length?creators.map(card).join(''):`<div class="video-empty compact"><div class="video-empty-icon">🎬</div><b>NOCH NICHT VERFÜGBAR</b><span>Noch keine freigegebenen Creator-Videos.</span></div>`}</div></section></main>`;
    if(typeof bindSounds==='function')bindSounds();
  }
  async function renderAccountV26(){
    const d=await me();
    if(!d.loggedIn){ if(typeof renderAccount==='function') return renderAccount(); return; }
    $('#app').innerHTML=`<main class="page account-page"><div class="page-head"><small>JANIBOYGAMES ACCOUNT</small><h1>MEIN KONTO</h1><p>Dein Konto ist per E-Mail-Bestätigung geschützt.</p></div><div id="accountPanel" class="account-panel"><div class="loading">Konto wird geladen…</div></div></main>`;
    const panel=$('#accountPanel');
    let inv={pets:[],updatedAt:null};try{const r=await fetch('/api/player-index',{cache:'no-store'});if(r.ok)inv=await r.json()}catch{}
    const role=d.user?.role||'user';
    const roleLabel=role==='admin'?'ADMINISTRATOR':role==='creator'?'CONTENT CREATOR':'MITGLIED';
    const creatorBox=role==='admin'?`<div class="creator-tools"><b>ADMIN-BEREICH</b><span>Du kannst Creator, Videos, Konten und Sicherheit verwalten.</span><a class="btn primary" href="#admin">ADMIN PANEL ÖFFNEN</a></div>`:role==='creator'?`<div class="creator-tools"><b>CONTENT CREATOR</b><span>Du bist freigegeben. Schicke Video-Links ein; sie werden erst nach Admin-Freigabe öffentlich.</span><form id="creatorVideoForm"><input name="title" maxlength="100" required placeholder="Videotitel"><input name="url" type="url" required placeholder="YouTube-Link"><button class="btn primary">VIDEO EINREICHEN</button></form><small>Jeder Link wird vor der Veröffentlichung geprüft.</small></div>`:`<div class="creator-tools"><b>CONTENT CREATOR WERDEN</b><span>Nur vom Administrator freigegebene Creator dürfen Links einreichen.</span>${d.user?.creatorRequested?'<div class="creator-pending">Anfrage bereits gesendet ✓</div>':'<button class="btn" id="creatorRequestBtn">CREATOR-ANFRAGE SENDEN</button>'}</div>`;
    panel.innerHTML=`<div class="account-card big"><div class="account-avatar">${esc2((d.user?.email||'JB').slice(0,2).toUpperCase())}</div><div><small>${roleLabel}</small><h2>${esc2(d.user?.email||'Konto')}</h2><p>${d.user?.verified?'E-Mail bestätigt ✓':'E-Mail noch nicht bestätigt'}<br>${d.robloxUser?`Roblox: ${esc2(d.robloxUser.name)} · User ID ${esc2(d.robloxUser.userId)}`:'Roblox noch nicht verbunden'}<br>Letzter Sync: ${esc2(inv.updatedAt||'noch nicht')}</p></div><div class="account-actions"><button class="btn primary" onclick="connectRoblox()">${d.robloxUser?'ROBLOX VERBUNDEN':'ROBLOX VERBINDEN'}</button><button class="btn" onclick="location.hash='account'">↻ AKTUALISIEREN</button><button class="btn" onclick="logoutAccountV26()">ABMELDEN</button></div></div>${creatorBox}<section class="account-inventory"><div class="section-title"><div><small>DEIN ROBLOX-SPIEL-INDEX</small><h2>${(inv.pets||[]).length} ERKANNTE PETS</h2></div><span class="section-note">Nur dein Game-Sync</span></div><div class="pet-grid"><div class="empty"><b>Roblox-Sync aktiv</b><span>Die Inventaransicht bleibt bei echten Game-Daten. Es werden keine Pets erfunden.</span></div></div></section>`;
    $('#creatorRequestBtn')?.addEventListener('click',async()=>{const r=await fetch('/api/account/request-creator',{method:'POST'});const x=await r.json();toast(x.message||'');if(x.success)renderAccountV26()});
    $('#creatorVideoForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const r=await fetch('/api/creator/videos',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:f.get('title'),url:f.get('url')})});const x=await r.json();toast(x.message||'');if(x.success)e.currentTarget.reset()});
    bindSounds?.();
  }
  window.logoutAccountV26=async()=>{await fetch('/api/auth/logout',{method:'POST'});location.hash='account';location.reload()};
  async function renderAdmin(){
    const d=await me();if(!d.loggedIn||d.user?.role!=='admin'){location.hash='account';setTimeout(()=>toast('Admin-Bereich nur für das Administrator-Konto.'),50);return}
    $('#app').innerHTML=`<main class="page admin-page"><div class="page-head"><small>JANIBOYGAMES CONTROL CENTER</small><h1>ADMIN PANEL</h1><p>Vollständige Moderation für Konten, Content Creator, Videos und Sicherheitsprotokolle.</p></div><div id="adminStats" class="admin-stats"><div class="loading">Dashboard wird geladen…</div></div><div class="admin-grid"><section class="admin-card"><div class="admin-card-head"><div><small>CONTENT MODERATION</small><h2>Video-Anfragen</h2></div><button class="btn" onclick="loadAdminVideosV26()">↻</button></div><div id="adminVideos" class="admin-list"><div class="loading">Laden…</div></div></section><section class="admin-card"><div class="admin-card-head"><div><small>CREATOR MANAGEMENT</small><h2>Konten & Rollen</h2></div><button class="btn" onclick="loadAdminAccountsV26()">↻</button></div><div id="adminAccounts" class="admin-list"><div class="loading">Laden…</div></div></section><section class="admin-card full"><div class="admin-card-head"><div><small>TRAILER / VIDEO</small><h2>Video direkt freigeben</h2></div></div><form id="adminVideoForm" class="admin-form"><select name="type"><option value="trailer">Trailer</option><option value="creator">Creator Video</option></select><input name="title" maxlength="100" required placeholder="Titel"><input name="creator" maxlength="80" placeholder="Creator"><input name="url" type="url" required placeholder="YouTube-Link"><button class="btn primary">VERÖFFENTLICHEN</button></form></section><section class="admin-card full"><div class="admin-card-head"><div><small>SECURITY</small><h2>Sicherheitsprotokoll</h2></div><button class="btn" onclick="loadAdminAuditV26()">↻</button></div><div id="adminAudit" class="admin-list"><div class="loading">Laden…</div></div><div class="admin-security-actions"><button class="btn" onclick="logoutAllV26()">ANDERE SITZUNGEN ABMELDEN</button><span>Sessions sind serverseitig, HttpOnly und zeitlich begrenzt.</span></div></section></div></main>`;
    $('#adminVideoForm').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const r=await fetch('/api/admin/videos',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(f.entries()))});const x=await r.json();toast(x.message|| (x.success?'Video veröffentlicht.':'Fehler'));if(x.success){e.currentTarget.reset();loadAdminVideosV26();loadAdminStatsV26()}});
    await Promise.all([loadAdminStatsV26(),loadAdminVideosV26(),loadAdminAccountsV26(),loadAdminAuditV26()]);bindSounds?.();
  }
  window.loadAdminStatsV26=async()=>{try{const r=await fetch('/api/admin/overview',{cache:'no-store'}),d=await r.json();if(!d.success)throw 0;$('#adminStats').innerHTML=Object.entries(d.stats).map(([k,v])=>`<div class="admin-stat"><small>${esc2(k.replace(/([A-Z])/g,' $1').toUpperCase())}</small><strong>${Number(v).toLocaleString('de-DE')}</strong></div>`).join('')}catch{$('#adminStats').innerHTML='<div class="empty">Dashboard konnte nicht geladen werden.</div>'}};
  window.loadAdminVideosV26=async()=>{try{const r=await fetch('/api/admin/videos',{cache:'no-store'}),d=await r.json();const vs=d.videos||[];$('#adminVideos').innerHTML=vs.length?vs.map(v=>`<div class="admin-row"><div><b>${esc2(v.title)}</b><span>${esc2(v.creator||'')} · ${esc2(v.status)} · ${esc2(v.url)}</span></div><div class="admin-row-actions">${v.status!=='approved'?`<button class="btn mini" onclick="moderateVideoV26('${v.id}','approved')">✓ FREIGEBEN</button>`:''}${v.status!=='rejected'?`<button class="btn mini" onclick="moderateVideoV26('${v.id}','rejected')">✕ ABLEHNEN</button>`:''}<button class="btn mini danger" onclick="deleteVideoV26('${v.id}')">LÖSCHEN</button></div></div>`).join(''):'<div class="empty">Keine Video-Anfragen.</div>'}catch{$('#adminVideos').innerHTML='<div class="empty">Nicht erreichbar.</div>'}};
  window.moderateVideoV26=async(id,status)=>{const r=await fetch('/api/admin/videos/'+encodeURIComponent(id)+'/status',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});const d=await r.json();toast(d.message|| (d.success?'Gespeichert.':'Fehler'));if(d.success){loadAdminVideosV26();loadAdminStatsV26()}};
  window.deleteVideoV26=async id=>{if(!confirm('Dieses Video wirklich löschen?'))return;const r=await fetch('/api/admin/videos/'+encodeURIComponent(id),{method:'DELETE'});const d=await r.json();toast(d.success?'Gelöscht.':'Fehler');if(d.success){loadAdminVideosV26();loadAdminStatsV26()}};
  window.loadAdminAccountsV26=async()=>{try{const r=await fetch('/api/admin/accounts',{cache:'no-store'}),d=await r.json();$('#adminAccounts').innerHTML=(d.accounts||[]).map(a=>`<div class="admin-row"><div><b>${esc2(a.email)}</b><span>${esc2(a.role)} · ${a.verified?'E-Mail bestätigt':'E-Mail offen'}${a.creatorRequested?' · CREATOR-ANFRAGE':''}</span></div><div class="admin-row-actions">${a.role!=='admin'?`<button class="btn mini" onclick="setCreatorV26('${a.id}',${a.role==='creator'?'false':'true'})">${a.role==='creator'?'CREATOR ENTZIEHEN':'ALS CREATOR FREIGEBEN'}</button>`:''}${a.role!=='admin'?`<button class="btn mini danger" onclick="deleteAccountV26('${a.id}')">LÖSCHEN</button>`:''}</div></div>`).join('')||'<div class="empty">Keine Konten.</div>'}catch{$('#adminAccounts').innerHTML='<div class="empty">Nicht erreichbar.</div>'}};
  window.setCreatorV26=async(id,approved)=>{const r=await fetch('/api/admin/accounts/'+encodeURIComponent(id)+'/creator',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({approved})});const d=await r.json();toast(d.success?'Rolle geändert.':d.message||'Fehler');if(d.success){loadAdminAccountsV26();loadAdminStatsV26()}};
  window.deleteAccountV26=async id=>{if(!confirm('Konto wirklich löschen?'))return;const r=await fetch('/api/admin/accounts/'+encodeURIComponent(id),{method:'DELETE'});const d=await r.json();toast(d.success?'Konto gelöscht.':d.message||'Fehler');if(d.success){loadAdminAccountsV26();loadAdminStatsV26()}};
  window.loadAdminAuditV26=async()=>{try{const r=await fetch('/api/admin/audit',{cache:'no-store'}),d=await r.json();$('#adminAudit').innerHTML=(d.audit||[]).map(x=>`<div class="admin-row"><div><b>${esc2(x.action)}</b><span>${esc2(x.time)} · ${esc2(JSON.stringify(x.meta||{}))}</span></div></div>`).join('')||'<div class="empty">Noch keine Einträge.</div>'}catch{$('#adminAudit').innerHTML='<div class="empty">Nicht erreichbar.</div>'}};
  window.logoutAllV26=async()=>{const r=await fetch('/api/admin/logout-all',{method:'POST'});const d=await r.json();toast(d.success?'Andere Sitzungen wurden abgemeldet.':'Fehler');};
  function route(){const r=location.hash.replace('#','').split('/')[0]||'home';if(r==='admin')return renderAdmin();if(r==='videos')return renderVideos();if(r==='account')return renderAccountV26();}
  window.addEventListener('hashchange',()=>{const r=location.hash.replace('#','').split('/')[0];if(['admin','videos','account'].includes(r))setTimeout(route,10)});
  const initial=location.hash.replace('#','').split('/')[0];if(['admin','videos','account'].includes(initial))setTimeout(route,20);
})();
